### ISSUE TITLE
Not pulling/syncing watch history while in playlists.

### ISSUE THREAD

**Issue by GaabluhnMowd** [sniklaus/youtube-watchmarker#138]
Seems that Watchmarker is not pulling history as it did in previous version (4.4.2) when on a playlist - it only seems to catch up on history when you navigate to a different page or manually sync.  I've noticed this behaviour on every version I've tried since 4.4.2, whereas with that version, as soon as the  next video was played, watchmarker would add it to it's database.  Is this behaviour (change) intentional?

My settings.  I have tried turning on marking as soon as player reports activity, but it makes no difference.

![Image](https://github.com/user-attachments/assets/64377720-62b2-4b0c-b4b5-a1f3c7906fbd)

**Comment by sniklaus** [comment]
I just released version `5.0.0` (already live on Firefox, pending review on Chrome) with manifest v3 support as well as fixes due to breaking changes in the Youtube page layout. As such, I am under the impression that this issue is resolved which is why I am closing it for now. Should I be mistaken then please do not hesitate to let me know, happy to reopen it again.

**Comment by GaabluhnMowd** [comment]
Issue persists, unfortunately.  Seems like a sync to YT history isn't triggered until navigation, perhaps it's a YT SPA issue?
