### ISSUE TITLE
History Synchronization Discrepancy 

### ISSUE THREAD

**Issue by mkruer** [sniklaus/youtube-watchmarker#32]
In the past I have been using the YouTubeCenter videoHistory to filter out watched videos and I am seeing a major discrepancy between youtube-watchmarker and YouTubeCenter. YouTubeCenter having the superior filter. 

Right now with both active the YouTubeCenter shows 103 watched videos out of 120 videos, whereas youtube-watchmarker after running the sync only detected 3 videos were watched on one channel over the past 3 months. This might be down to how youtube-watchmarker is importing watched data or some missing matches when running the synchronization process.

To make your life easier I an including a link to the YouTubeCenter match method
Line: 3677-3722 ytcenter.videoHistory
https://raw.githubusercontent.com/YePpHa/YouTubeCenter/master/dist/YouTubeCenter.js

Keep up the good work.

**Comment by sniklaus** [comment]
How did you sync Youtube Watchmarker?

**Comment by mkruer** [comment]
Clicked on the icon on the taskbar, it opened the youtube-watchmarker the extension page in the browser. Ran the History Sync.

Message: 	finished synchronizing
Progress: 	966 - 6 were new

If I run the sync again, i get the same message. That is why i am wondering if there is a bug in the history search. below is a quick and dirty sample. 

https://www.youtube.com/channel/UCX_t3BvnQtS5IHzto_y7tbw/videos?disable_polymer=1
https://www.youtube.com/watch?v=mHKDZmithRA (YouTubeCenter only)
https://www.youtube.com/watch?v=IfHG7bj-CEI (youtube-watchmarker only)
https://www.youtube.com/watch?v=c2uoO_vBUKs (Both)

If I go to Firefox's history and to a simple lookup for all youtube history (Search https://www.youtube.com/watch?v) , It shows 25577 items.

**Comment by sniklaus** [comment]
Interesting find, thanks for sharing! I will look into this further when I work on the next version. 👍

**Comment by mkruer** [comment]
Not a problem. let me know if you need some help in debugging let me know. I haven't done JS is forever, but I think I remember enough to read the code and do some debugging.  

Side note: Another lower P issue might also be Mozilla does not recommend this Extension, but not quite sure why. The source is open and there doesn't appear to be anything fishy. It might just be because of amount access of date you are looking to parse?


https://addons.mozilla.org/en-US/firefox/addon/yourect/?src=search
This is not a Recommended Extension. Make sure you trust it before installing

**Comment by sniklaus** [comment]
Thank you for the heads up regarding the listing! I haven't updated the extension in a while and they tend to change the approval process. Maybe they made it more strict now and all old listings that haven't gone through the more thorough process are listed like this. I will address it once the new version is finished.

**Comment by sniklaus** [comment]
I just released a new version, would you mind giving the browser history synchronization a try again? I am looking forward to hearing whether or not it fully works for you now, thanks!

**Comment by mkruer** [comment]
It is still showing imported 3383 videos - 6 were new, my current count is 26959 from my History. Instead of outputting to a database file is there a way to export it as a flat list (txt or cvs)

**Comment by sniklaus** [comment]
Thank you for giving it another try! For each entry in the history, the following is checked.

```
if (objResult.url.indexOf('https://www.youtube.com/watch?v=') !== 0) {
	continue;

} else if ((objResult.title === undefined) || (objResult.title === null)) {
	continue;

} else if (objResult.title.indexOf(' - YouTube') !== objResult.title.length - 10) {
	continue;

}
```

in other words, the URL needs to start with `'https://www.youtube.com/watch?v=`, the title must be valid, and the title must end with ` - YouTube`. Would you mind checking some of the entries of your browser history to see what may go wrong?

I am afraid that there is no export as a flat list. However, the following Python script should allow you to open and iterate over the videos in an exported database.

```
import base64
import json

for objVideo in json.loads(base64.b64decode(open('CHANGETHIS.database', 'r').read())):
    print(objVideo)
# end
```

**Comment by mkruer** [comment]
Ok I think I see issue. In the history not all the tiles of the URL ended with `- YouTube` some where just the Title without the `- YouTube` I don't know if this was a recent addition. If I revisit the page, then it will add in the `- YouTube` at the end of the title and track this. This looks like YouTube shenanigans, 

1. What was the purpose of the additional check? 
2. Is it required?
3. Is there a better way to handle this exception?

I am not a java programmer, if this was a simple regex expression just adding ^ would then require the URL to start with the required `https://www.youtube.com/watch?v=` this would discard and youtube that might be embedded in a URL

**Comment by sniklaus** [comment]
I will remove this additional check in the next version. Please ping me in case I have not released the new version within the next two weeks. I am currently waiting to get some feedback for the other bug fixes that the newest release brought, maybe there are more changes that I should include in the next release.

**Comment by mkruer** [comment]
OK will do, thanks for the updates.  I added to comment #18 on how to address the watched issue. It might require a bit more research but it is a start.

**Comment by sniklaus** [comment]
I just released a new version with the third condition removed. Would you mind giving it another try and letting me know whether the extension is importing more videos from your browser history now? Thanks!

**Comment by sniklaus** [comment]
Closing for now since I am under the impression that this issue has been fixed with the newest version. Please let me know in case the problem has not been resolved, thanks!

**Comment by mkruer** [comment]
[Verified Fixed] "imported 26835 videos - 21463 were new" I am seeing in the youtube feed some of the videos recommended are now marked as watched that were not before.

**Comment by sniklaus** [comment]
Awesome, thanks for confirming!
